### ISSUE TITLE
errors not reported when multiple statements in a query

### ISSUE THREAD

**Issue by dennisobrien** [uber/vertica-python#124]
When `cursor.execute` is passed a query that has multiple statements, and one of the statements results in a database error, that error is not raised (unless it is the first statement).

Here's an example of a query that when run on its own raises a `MissingColumn` exception:

```
import vertica_python

params = get_default_db_params()
connection = vertica_python.connect(**params)
cursor = connection.cursor()
cursor.execute('select a;')  # bad query to raise and exception
```

When this query is among multiple statements (and not the first statement) no error is raised.

```
cursor.execute('select 1; select a;')
```

The expected results is a `MissingColumn` exception.

For reference, pyodbc raises a `ProgrammingError`, and jaydebeapi raises a `java.sql.SQLSyntaxErrorExceptionPyRaisable`.

Tested with vertica_python 0.6.3 on Python 2.7.11+ and Python 3.5.1+, with Vertica 7.2.3 db.

**Comment by thomastygreat** [comment]
I have found a workaround for this issue.
I'm not sure it works in every situation, but the first tests seem to be ok.

It would be nice to fix it in the driver though :)

`
import vertica_python
import vertica_python.vertica.messages as messages

def executeQuery(sqlQuery):
	connection = getConnection()
	cur = connection.cursor()
	cur.execute(sqlQuery)
	checkErrorMessage(cur.connection)
	connection.commit()
	connection.close()

def checkErrorMessage(connection):
	while True:
		message = connection.read_message();
		if isinstance(message, messages.ErrorResponse):
			connection.rollback()
			connection.close()
			raise Exception(message.error_message()) 
		# this message is always the last in the stack
		if isinstance(message, messages.ReadyForQuery):
			break
`

**Comment by alexjikim** [comment]
as of 0.7.1 this should be fixed, but the behavior is a bit different than what you are seeing in pyodbc.

cur.execute("SELECT 1; SELECT a;")
# first we need to read results from the first executed statement
res1 = cur.fetchall()
cur.fetchone() # returns None

# ask for the next set of data:
cur.nextset()  # will (as of 0.7.1) throw an error
res2 = cur.fetchall()  # would work if no error on nextset()

**Comment by nchammas** [comment]
@alexjikim - This will only work with SELECT statements, correct? If the second statement is something else, this won't work, as reported in #185.

**Comment by alexjikim** [comment]
@nchammas  yea i think thats correct

**Comment by phillynch7** [comment]
Problem still exists in 0.7.3.
```
import vertica_python
vertica_python.__version__
# '0.7.3'

conn = vertica_python.connect(**conn_info)
cur.execute('select count(*) from myschema.mytable; select abc from abc;')
```
myschema.mytable is a real table, but table/column abc do not exist. This returns no error.
